import { AuthProvider } from "@/components/AuthProvider";
import HeaderWithSession from "@/components/HeaderWithSession";
import { Fredoka } from "next/font/google";
import Footer from "../components/Footer";
import "../styles/globals.css";

const fredoka = Fredoka({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={fredoka.className}>
          {/* <Header /> */}
          <HeaderWithSession />
          <main className="flex-grow">
            {children} {/* Main content goes here */}
          </main>
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
