import localFont from "next/font/local";
import Footer from "../components/Footer";
import Header from "../components/Header";
import "../styles/globals.css";
import { Fredoka } from "next/font/google";
import { cn } from "@/lib/utils";

const fredoka = Fredoka({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="flex-grow">
          {children} {/* Main content goes here */}
        </main>
        <Footer />
      </body>
    </html>
  );
}
